services:
  - type: web
    name: furima-47502
    env: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rails db:migrate
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}
    preDeployCommand: bundle exec rails db:migrate
